name: Publish to PyPI
on:
  push:
    # branches:
    #   - main
    tags:
      - v* # Trigger on tags starting with "v" (e.g., v1.0.0)
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.10" # Or your desired Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel twine
      - name: Build package
        run: python -m pip install .
      - name: Build sdist and bdist_wheel
        run: python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__ 
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # Use the stored PyPI token
        run: |
          twine upload dist/*